[package]
name = "api"
version = "0.1.0"
edition = "2021"

[dependencies]
prost = "0.11.0"
prost-types = "0.11.1"
tonic.workspace = true

[build-dependencies]
tonic-build = { version = "0.8", default-features = false, features = ["prost", "transport"] }
